spring.application.name=T_shirt_web
spring.datasource.url=jdbc:postgresql://localhost:5432/tshirt_shop
spring.datasource.username=postgres
spring.datasource.password=87257866ca
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=3000
spring.jpa.properties.hibernate.format_sql=true